# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-20 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentinfo', '0002_auto_20190219_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
